language: python
sudo: false
python:
  - "3.6"
cache: pip

install:
  - pip install -r backend/requirements.txt
  - pip install -r backend/test/requirements.txt

script:
  - PYTHONPATH=backend python backend/test/chain/test_board.py
  - PYTHONPATH=backend python backend/test/flask/test_retro_api.py
  - PYTHONPATH=backend python backend/test/store/test_redis_store.py
