language: python
sudo: false
python:
  - "3.6"
cache: pip

install:
  - pip install -r backend/requirements.txt
  - pip install -r backend/test/requirements.txt

script:
  - PYTHONPATH=backend python backend/test/unit/chain/test_board.py
  - PYTHONPATH=backend python backend/test/unit/engine/test_board_engine.py
  - PYTHONPATH=backend python backend/test/unit/store/test_redis_store.py
  - PYTHONPATH=backend python backend/test/integration/flask/test_retro_api.py
