language: python
sudo: false
python:
  - "3.6"
cache: pip

before_install:
  - cd backend

install:
  - pip install -r backend/requirements.txt
  - pip install -r backend/test/requirements.txt

before_script:
  - cd backend

script:
  - python backend/test/chain/test_board.py
  - python backend/test/flask/test_retro_api.py
  - python backend/test/store/test_redis_store.py
