
version: '3'
services:
  web:
    build: ./backend
    links:
      - redis
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEMPLATE_CONFIG=/app/conf/templates.cfg
  redis:
    image: redis:4
    ports:
      - "6379:6379"
