
version: '3'
services:
  web:
    build: ./backend
    links:
      - redis
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:3
    ports:
      - "6379:6379"
