
version: '3'
services:
  api:
    build:
        context: ./backend/
        dockerfile: Dockerfile.api
    ports:
      - "80:80"
    environment:
      - RETRO_HOME=/app
  websocket:
    build:
        context: ./backend/
        dockerfile: Dockerfile.websocket
    ports:
      - "5124:5124"
    environment:
      - RETRO_HOME=/app
  redis:
    image: redis:4-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ${PWD}/backend/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
